name: build immortalwrt for tr3000

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    name: build immortalwrt for tr3000
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache dependencies
        uses: actions/cache@v4
        id: cache-deps
        with:
          path: ~/.cache/apt
          key: ${{ runner.os }}-apt-cache-${{ hashFiles('**/apt-install.txt') }}
          restore-keys: |
            ${{ runner.os }}-apt-cache-

      - name: Install dependencies
        if: steps.cache-deps.outputs.cache-hit != 'true'
        env:
          DEBIAN_FRONTEND: noninteractive
        run: sudo -E apt install build-essential clang flex bison g++ gawk gcc-multilib g++-multilib gettext git libncurses5-dev libssl-dev python3-setuptools rsync swig unzip zlib1g-dev file wget

      - name: Cache immortalwrt source code
        uses: actions/cache@v4
        id: cache-immortalwrt
        with:
          path: immortalwrt
          key: ${{ runner.os }}-immortalwrt-${{ hashFiles('**/immortalwrt-version.txt') }}  # 使用版本文件的哈希值
          restore-keys: |
            ${{ runner.os }}-immortalwrt-

      - name: Clone immortalwrt source code
        if: steps.cache-immortalwrt.outputs.cache-hit != 'true'
        run: |
          git clone https://github.com/immortalwrt/immortalwrt.git
          cd immortalwrt
          git checkout v24.10.2  # 更新为新版本
          echo "src-git nikki https://github.com/nikkinikki-org/OpenWrt-nikki.git;main" >> "feeds.conf.default"

      - name: Update the feeds
        run: |
          cd immortalwrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Copy config file
        run: |
          cp .config immortalwrt/
          cp mt7981b-cudy-tr3000-v1-ubootmod.dts immortalwrt/target/linux/mediatek/dts/

      - name: Cache downloaded packages
        uses: actions/cache@v4
        id: cache-downloads
        with:
          path: immortalwrt/dl
          key: ${{ runner.os }}-downloads-${{ hashFiles('immortalwrt/.config') }}
          restore-keys: |
            ${{ runner.os }}-downloads-

      - name: make download
        env:
          FORCE_UNSAFE_CONFIGURE: 1
        run: |
          cd immortalwrt
          make defconfig
          make download

      - name: make
        env:
          FORCE_UNSAFE_CONFIGURE: 1
        run: |
          cd immortalwrt
          make -j8

      - name: zip the bin
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r immortalwrt-tr3000.zip immortalwrt/bin

      - name: Release and Upload
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: immortalwrt-tr3000.zip
        
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 2

      - name: Remove old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 3
          delete_tags: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
